name: Build/Test/Push

on: 
  push:
    branches:
      - devel
      - main
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish container images
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v2

      - name: Set Github variables
        id: vars
        run: ./github-vars

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: neale
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Currently required, because buildx doesn't support auto-push from docker
      - name: Set up builder
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push moth-devel image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          target: devel-server
          file: Containerfile
          push: true
          context: contrib/python/
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          tags: |
            dirtbags/moth-devel:${{ steps.vars.outputs.tag }}
            ghcr.io/dirtbags/moth-devel:${{ steps.vars.outputs.tag }}
